### ISSUE TITLE
/bin/sh: sanitycheck: command not found

### ISSUE THREAD

**Issue by othiym23** [jden/quality#1]
[ohhh noooooooo....](https://www.youtube.com/watch?v=Ox0xn5YHe1Q)

```
bauchelain% npm -g i quality
/usr/local/bin/quality -> /usr/local/lib/node_modules/quality/index.js
quality@1.0.3 /usr/local/lib/node_modules/quality
├── shelljs@0.5.1
├── sanitycheck@2.0.2 (xtend@4.0.0, depscan@0.4.1, valiquire-silent@0.3.1)
└── standard@4.1.0 (get-stdin@4.0.1, uniq@1.0.1, find-root@0.1.1, xtend@4.0.0, eslint-config-standard-react@1.0.0, eslint-config-standard@3.1.0, run-parallel@1.1.1, ignore@2.2.15, minimist@1.1.1, eslint-plugin-react@2.5.0, dezalgo@1.0.2, glob@5.0.10, standard-format@1.3.6, eslint@0.22.1)
bauchelain% quality
/bin/sh: sanitycheck: command not found
bauchelain% rehash
bauchelain% quality
/bin/sh: sanitycheck: command not found
bauchelain% npm --version && node --version
2.11.2
v2.0.2
```

**Comment by othiym23** [comment]
(also I think this is a fantastic idea and you are a fantastic person for putting it together)

**Comment by junosuarez** [comment]
I just republished 1.0.4 - can you retry?

**Comment by othiym23** [comment]
With 1.0.5:

```
bauchelain% quality
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/Users/ogd/Documents/projects/npm/npm/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:399:15)
    at depscan.readFile (/usr/local/lib/node_modules/quality/node_modules/sanitycheck/node_modules/depscan/main.js:124:18)
    at /usr/local/lib/node_modules/quality/node_modules/sanitycheck/node_modules/depscan/main.js:97:14
    at Array.forEach (native)
    at depscan.check (/usr/local/lib/node_modules/quality/node_modules/sanitycheck/node_modules/depscan/main.js:92:11)
    at depscan.go (/usr/local/lib/node_modules/quality/node_modules/sanitycheck/node_modules/depscan/main.js:66:14)
    at new depscan (/usr/local/lib/node_modules/quality/node_modules/sanitycheck/node_modules/depscan/main.js:27:10)
    at depscan (/usr/local/lib/node_modules/quality/node_modules/sanitycheck/node_modules/depscan/main.js:7:16)
```

So, progress!

**Comment by friday** [comment]
Same here. My project has a package.json with a "main" entry "app.js", but quality expects it to be index.js. When I renamed in order to test it further it crashes on the first package I'm using for the same reason.

**Comment by max-k** [comment]
Same here, my sources are stored in src directory and quality still search them in the root directory.
